### ISSUE TITLE
指定出口

### ISSUE THREAD

**Issue by M4gics** [0990/socks5#1]
本地建立服务端口 接收到的请求怎么使用socks5的代理去访问，类似于负载均衡

**Comment by 0990** [comment]
你是想将tcp流量转成socks5流量吗，可以参见client.go及client_test.go的代码

**Comment by 0990** [comment]
不明白你的需求，“服务器使用我准备好的大量socks5将每个请求都加上代理去访问”是什么意思，你不是已经在服务器搭建了socks5服务端了吗，这个“加上代理”是指什么

**Comment by M4gics** [comment]
和负载均衡类似，到服务器的请求，这里假设都为web请求，我希望服务器端在这个web请求上再加上其他的socks代理去访问，能理解吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [0990/socks5] 指定出口 (#1)





 
不明白你的需求，“服务器使用我准备好的大量socks5将每个请求都加上代理去访问”是什么意思，你不是已经在服务器搭建了socks5服务端了吗，这个“加上代理”是指什么
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0990** [comment]
你是客户端请求到服务器A,你希望服务器A将此请求通过socks代理，转到B,C,D等服务器，是这个意思吗

**Comment by M4gics** [comment]
对的，我希望实现反向的负载均衡，服务器A将请求通过socks代理去访问，我尝试查了很多文章没有这样的案例，希望能有demo指导学习，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 上午10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [0990/socks5] 指定出口 (#1)





 
你是客户端请求到服务器A,你希望服务器A将此请求通过socks代理，转到B,C,D等服务器，是这个意思吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0990** [comment]
那不一定要用socks5,你想要的可能是这个：https://github.com/fatedier/frp/issues/605

**Comment by M4gics** [comment]
这有浏览到，直接再socks5服务端中不能解决这个问题吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 上午10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [0990/socks5] 指定出口 (#1)





 
那不一定要用socks5,你想要的可能是这个：fatedier/frp#605
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0990** [comment]
应该可以，但较麻烦，服务器A上，需要部署socks5服务(假设端口1080),流量转发服务(假设端口8080），这个流量转发服务需要自己写，客户端连接8080，流量转发服务接收新连接后，要用client.go将流量转成socks5流量，Dial方法中将BCD三个服务器的服务地址（ip+端口）轮流填入，可以达到负载均衡效果

**Comment by M4gics** [comment]
初学。。有点难，有类似的demo吗
