### ISSUE TITLE
Socks5 usage

### ISSUE THREAD

**Issue by bannyhm** [0990/socks5#12]
Hello.

I'm trying to use ss5 on the frpc client instead of the socks5 plugin built into FRP. But I am getting the following error:

{
    "ListenPort": 6395,
    "TCPListen": "127.0.0.1:6395",
    "UDPListen": "127.0.0.1:6395",
    "UDPAdvertisedIP": "",
    "UserName": "user",
    "Password": "user",
    "UDPTimout": 60,
    "TCPTimeout": 60,
    "LogLevel": "debug"
}

./ss5 -c ./ss5.json
time="2023-09-04 15:13:58" level=info msg="Server Config:{ListenPort:6395 TCPListen:127.0.0.1:6395 UDPListen:127.0.0.1:6395 UDPAdvertisedIP: UserName:user Password:user UDPTimout :60 TCPTimeout:60 LogLevel:debug}"
time="2023-09-04 15:15:48" level=debug msg="tcp req:chek.zennolab.com:80"
time="2023-09-04 15:15:48" level=debug msg="connect to chek.zennolab.com:80 failed" error="dial tcp: lookup chek.zennolab.com on [::1]: 53: read udp [::1]:60074->[::1]:53: read: connection refused"
time="2023-09-04 15:17:03" level=debug msg="tcp req:ip.bablosoft.com:80"
time="2023-09-04 15:17:03" level=debug msg="connect to ip.bablosoft.com:80 failed" error="dial tcp: lookup ip.bablosoft.com on [::1]: 53: read udp [::1]:40409->[::1]:53: read: connection refused"
time="2023-09-04 15:17:03" level=debug msg="tcp req:ip2.bablosoft.com:443"
time="2023-09-04 15:17:03" level=debug msg="connect to ip2.bablosoft.com:443 failed" error="dial tcp: lookup ip2.bablosoft.com on [::1]: 53: read udp [::1]:33079->[::1]:53: read: connection refused"

Please tell me how I can fix this error in order to use your solution successfully.

my frps server config:

[common]
bind_addr = 0.0.0.0
bind_port = 9300
kcp_bind_port = 9300
dashboard_addr = 0.0.0.0
dashboard_port = 9500
dashboard_user = user
dashboard_pwd = user
enable_prometheus = true
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false
authenticate_new_work_conns = false
token = 12345678
oidc_issuer =
oidc_audience =
oidc_skip_expiry_check = false
oidc_skip_issuer_check = false
allow_ports = 2000-7000,7001,7003,8000-60000
max_pool_count = 0
max_ports_per_client = 0
tls_only=false
subdomain_host=frps.com
tcp_mux=true
udp_packet_size = 1500
dns_server = 0.0.0.0

frpc client configuration:
[common]
forward_all = tcp+udp
all_use_encryption = false
all_use_compression = false
server_addr = xxx.xxx.xxx.xxx
server_port = 9300
plugin_user = user
plugin_passwd = user
authentication_method = token
token = 12345678

udp_forward=true

[web_tcp6395]
type=tcp
local_ip = 127.0.0.1
local_port = 6395
remote_port = 6395
use_encryption=false
use_compression = false
protocol=tcp

[web_udp6395]
type=udp
local_ip = 127.0.0.1
local_port = 6395
remote_port = 6395
use_encryption=false
use_compression = false
protocol=udp

![Sheme0-1](https://github.com/0990/socks5/assets/72357001/6dd9b8da-fd80-491e-a12d-93540cabc2dc)

**Comment by 0990** [comment]
what do you want to do? combine frpc with socks5 for what?

**Comment by bannyhm** [comment]
I need my program running on Windows PC to visit sites with mobile phone ip addresses. (The program imitates mobile devices)

**Comment by 0990** [comment]
your web sites is run in your mobile and you want to access it ,right?

**Comment by bannyhm** [comment]
Sites open in a program on a Windows PC, only its ip address is needed from a mobile phone in order for sites to see this ip address in their metric.

**Comment by 0990** [comment]
your mobile want visit your home pc program,but your home pc don't have public ip ,so you use one server which have public ip B with frp,than you can visit your home pc program by B, right? and your socket protoccol is udp ?

**Comment by 0990** [comment]
I don't full understand, but if use socks5 server,It  can only be visit by socks5 client such as proxifier,SwitchyOmega

**Comment by bannyhm** [comment]
My home PC has a public ip address and an android emulator is running on it, in the android emulator I specify the proxy socks5://ip_server:port:user:password. Through this socks5 proxy, the android emulator connects to the mobile phone. But since the mobile phone's ip address is constantly changing, I have to use a tunnel between the mobile phone and the server (which has a public ip). And on the mobile phone, a socks5 server is running, and as a result, my android emulator program visits sites with the ip address of the mobile phone.

I'll give an example:
I open a browser in an android emulator on a Windows PC, visit several websites. After that, I change the ip address of the mobile phone. And I repeat this cycle again. Sites see that the visitor enters with the parameters (fingerprint, browser type, browser version) that I specified in the android emulator program, but at the same time they see the ip address of the mobile phone, and not the ip address of my home PC or the ip address of the FRP server.

**Comment by 0990** [comment]
I see, I want to ask some question:
1, does android emulator support socks5 proxy? have you test?
2, to use tunnel,your install frps in server and frpc in mobile,right?
3,your current  trouble is :udp have problem but tcp ok?

**Comment by 0990** [comment]
you can try this:
{
"ListenPort": 6395,
"TCPListen": "0.0.0.0:6395",
"UDPListen": "0.0.0.0:6395",
"UDPAdvertisedIP": "188.222.221.54",
"UserName": "user",
"Password": "user",
"UDPTimout": 60,
"TCPTimeout": 60,
"LogLevel": "debug"
}

**Comment by 0990** [comment]
when use udp proxy in socks5,socks5 server tell socks5 client the advetised udp ip which is your server 188.222.221.54, then socks5 client use 188.222.221.54:6395 to proxy udp,your should bind 188.222.221.54:6395 to your mobile socks5 server by frp

**Comment by 0990** [comment]
In your scene,UDPAdvertisedIP is empty, which cause notify udp  proxy is 127.0.0.1:6379 which cause android emulator can not access,for more see UDP ASSOCIATE Section(https://github.com/0990/socks5/blob/master/doc/rfc1928.txt)

**Comment by bannyhm** [comment]
> I see, I want to ask some question:
> 1, does android emulator support socks5 proxy? have you test?
> 2, to use tunnel,your install frps in server and frpc in mobile,right?
> 3,your current trouble is :udp have problem but tcp ok?

1. Yes
2. True
3. Yes. tcp works, udp doesn't work

![example](https://github.com/0990/socks5/assets/72357001/df2dbae1-2032-4438-a1f0-b85229ac0732)

**Comment by bannyhm** [comment]
Thank you very much. I'll try to figure it out. If you know what settings I need to make my scheme work with udp support, I would like to arrange for you to set up my scheme for me and I do not waste time on this. If you can help me, we can discuss the cost. There is telegram in my profile.

**Comment by 0990** [comment]
replace your ServerIP with UDPAdvertisedIP,than try,it should worked
{
"ListenPort": 6395,
"TCPListen": "0.0.0.0:6395",
"UDPListen": "0.0.0.0:6395",
"UDPAdvertisedIP": "188.222.221.54",
"UserName": "user",
"Password": "user",
"UDPTimout": 60,
"TCPTimeout": 60,
"LogLevel": "debug"
}

**Comment by bannyhm** [comment]
I get this in the log:

./ss5 -c ./ss51.json
time="2023-09-06 07:53:37" level=info msg="Server Config:{ListenPort:6395 TCPListen:[0.0.0.0:6395](https://0.0.0.0:6395/) UDPListen:[0.0.0.0:6395](https://0.0.0.0:6395/) UDPAdvertisedIP:[188.226.54.54](https://188.226.54.54/) UserName:user Password:user UDPTimout:60 TCPTimeout:60 LogLevel:debug}"
time="2023-09-06 07:54:01" level=debug msg="tcp req:[chek.zennolab.com:80](https://chek.zennolab.com:80/)"
time="2023-09-06 07:54:01" level=debug msg="connect to [chek.zennolab.com:80](https://chek.zennolab.com:80/) failed" error="dial tcp: lookup [chek.zennolab.com](https://chek.zennolab.com/) on [::1]:53: read udp [::1]:38627->[::1]:53: read: connection refused"
time="2023-09-06 07:55:33" level=debug msg="tcp req:[optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/)"
time="2023-09-06 07:55:33" level=debug msg="connect to [optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/) failed" error="dial tcp: lookup [optimizationguide-pa.googleapis.com](https://optimizationguide-pa.googleapis.com/) on [::1]:53: read udp [::1]:55131->[::1]:53: read: connection refused"
time="2023-09-06 07:55:33" level=debug msg="tcp req:[optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/)"
time="2023-09-06 07:55:33" level=debug msg="connect to [optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/) failed" error="dial tcp: lookup [optimizationguide-pa.googleapis.com](https://optimizationguide-pa.googleapis.com/) on [::1]:53: read udp [::1]:58987->[::1]:53: read: connection refused"
time="2023-09-06 07:55:33" level=debug msg="tcp req:[optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/)"
time="2023-09-06 07:55:33" level=debug msg="connect to [optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/) failed" error="dial tcp: lookup [optimizationguide-pa.googleapis.com](https://optimizationguide-pa.googleapis.com/) on [::1]:53: read udp [::1]:55657->[::1]:53: read: connection refused"
time="2023-09-06 07:55:33" level=debug msg="tcp req:[optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/)"
time="2023-09-06 07:55:33" level=debug msg="connect to [optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/) failed" error="dial tcp: lookup [optimizationguide-pa.googleapis.com](https://optimizationguide-pa.googleapis.com/) on [::1]:53: read udp [::1]:52274->[::1]:53: read: connection refused"

**Comment by 0990** [comment]
i have test your proxy, have found udp is ok now. But your mobile dns have some problem, can see by log"dial tcp: lookup [optimizationguide-pa.googleapis.com](https://optimizationguide-pa.googleapis.com/) on [::1]:53: read udp [::1]:58987->[::1]:53: read: connection refused"

**Comment by bannyhm** [comment]
Thank you. I will test this on other phones today. And I will turn to you again for help.

**Comment by bannyhm** [comment]
If I open the android emulator and try to load a page in a browser with ss5, then I get a dns error. But when I disable ss5 and enable the socks5 plugin built into FRP, I load this page. After loading the page, I turn off the socks5 plugin, turn on ss5 again, refresh the open page, and this page is refreshed, and in the logs I get this:

./ss5 -c ./ss5.json
time="2023-09-06 09:10:24" level=info msg="Server Config:{ListenPort:6390 TCPListen:[0.0.0.0:6390](https://0.0.0.0:6390/) UDPListen:[0.0.0.0:6390](https://0.0.0.0:6390/) UDPAdvertisedIP:[188.222.221.54](https://188.222.221.54/) UserName:user Password:user UDPTimout:60 TCPTimeout:60 LogLevel:debug}"
time="2023-09-06 09:10:35" level=debug msg="tcp req:[detect.id:443](https://detect.id/)"
time="2023-09-06 09:10:35" level=debug msg="connect to [detect.id:443](https://detect.id/) failed" error="dial tcp: lookup [detect.id](https://detect.id/) on [::1]:53: read udp [::1]:38369->[::1]:53: read: connection refused"
time="2023-09-06 09:10:35" level=debug msg="tcp req:[6.506639925.bash.ws:443](https://6.506639925.bash.ws/)"
time="2023-09-06 09:10:35" level=debug msg="connect to [6.506639925.bash.ws:443](https://6.506639925.bash.ws/) failed" error="dial tcp: lookup [6.506639925.bash.ws](https://6.506639925.bash.ws/) on [::1]:53: read udp [::1]:39411->[::1]:53: read: connection refused"
time="2023-09-06 09:10:35" level=debug msg="tcp req:[4.506639925.bash.ws:443](https://4.506639925.bash.ws/)"
time="2023-09-06 09:10:35" level=debug msg="tcp req:[1.506639925.bash.ws:443](https://1.506639925.bash.ws/)"
time="2023-09-06 09:10:35" level=debug msg="tcp req:[10.506639925.bash.ws:443](https://10.506639925.bash.ws/)"
time="2023-09-06 09:10:35" level=debug msg="connect to [1.506639925.bash.ws:443](https://1.506639925.bash.ws/) failed" error="dial tcp: lookup [1.506639925.bash.ws](https://1.506639925.bash.ws/) on [::1]:53: read udp [::1]:41018->[::1]:53: read: connection refused"
time="2023-09-06 09:10:35" level=debug msg="connect to [10.506639925.bash.ws:443](https://10.506639925.bash.ws/) failed" error="dial tcp: lookup [10.506639925.bash.ws](https://10.506639925.bash.ws/) on [::1]:53: read udp [::1]:39321->[::1]:53: read: connection refused"
time="2023-09-06 09:10:35" level=debug msg="tcp req:[8.506639925.bash.ws:443](https://8.506639925.bash.ws/)"
time="2023-09-06 09:10:35" level=debug msg="connect to [4.506639925.bash.ws:443](https://4.506639925.bash.ws/) failed" error="dial tcp: lookup [4.506639925.bash.ws](https://4.506639925.bash.ws/) on [::1]:53: read udp [::1]:49536->[::1]:53: read: connection refused"

![image](https://github.com/0990/socks5/assets/72357001/9ee4daca-0fda-4334-8f71-e59605d49695)

**Comment by bannyhm** [comment]
Yes, it's a magazine on the phone. There is no vpn enabled on the phone, I can open sites at the time of testing on this phone through the browser.

**Comment by 0990** [comment]
if these is container run ss5,what is the container's dns,It seem the container's dns is local[::53],but your system is not,can change container 's dns?

**Comment by bannyhm** [comment]
I am running this on the phone in termux from the root folder.

~ $ ./ss5 -c ./ss5.json
time="2023-09-06 10:15:46" level=info msg="Server Config:{ListenPort:6390 TCPListen:[0.0.0.0:6390](https://0.0.0.0:6390/) UDPListen:[0.0.0.0:6390](https://0.0.0.0:6390/) UDPAdvertisedIP:[188.222.221.54](https://188.222.221.54/) UserName:user Password:user UDPTimout:60 TCPTimeout:60 LogLevel:debug}"

**Comment by bannyhm** [comment]
i get this when checking dns:

time="2023-09-06 10:20:23" level=debug msg="connect to [optimizationguide-pa.googleapis.com:443](https://optimizationguide-pa.googleapis.com/) failed" error="dial tcp: lookup [optimizationguide-pa.googleapis.com](https://optimizationguide-pa.googleapis.com/) on [::1]:53: read udp [::1]:41852->[::1]:53: read: connection refused"                                               time="2023-09-06 10:20:26" level=error msg="conn handle" error=EOF
^Cquit,Got signal: interrupt                            

~ $ cat /etc/resolv.conf                                
cat: /etc/resolv.conf: No such file or directory        

~ $ cat /data/data/com.termux/files/usr/etc/resolv.conf
/data/data/com.termux/files/usr/etc/resolv.conf         
nameserver [8.8.8.8](https://8.8.8.8/)
nameserver [8.8.4.4](https://8.8.4.4/)

**Comment by 0990** [comment]
the ss5 is compiled by ubuntu? see https://github.com/termux/termux-app/issues/210#issue-194302836

**Comment by 0990** [comment]
solution is this https://github.com/termux/termux-app/issues/869#issuecomment-433986035

**Comment by bannyhm** [comment]
No, I downloaded the release:

https://github.com/0990/socks5/releases/download/v1.0.0/socks5_1.0.0_Linux_arm64.tar.gz

**Comment by 0990** [comment]
android version done,this should fix your problem: 
https://github.com/0990/socks5/releases/download/v1.0.5/socks5_1.0.5_android_arm64.tar.gz

**Comment by 0990** [comment]
I try android version,but the error occur same,the reason is  golang use /etc/resolv.conf but android not have,try this solution : 
https://github.com/termux/termux-app/issues/869#issuecomment-433985523

**Comment by bannyhm** [comment]
Thanks, I'm trying to figure this out right now.

**Comment by bannyhm** [comment]
Thank you. I succeeded partially, it remains to determine why udp is not detected.
![image](https://github.com/0990/socks5/assets/72357001/052a6908-b86f-475f-99e8-eae9a939790d)

Now I don't see udp connection

~ $ proot -b ./resolv.conf.temp:/etc/resolv.conf ./ss5 -c ./ss5.json
time="2023-09-06 16:28:08" level=info msg="Server Config:{ListenPort:6390 TCPListen:[0.0.0.0:6390](https://0.0.0.0:6390/) UDPListen:[0.0.0.0:6390](https://0.0.0.0:6390/) UDPAdvertisedIP:[188.226.54.54](https://188.226.54.54/) UserName:user Password:user UDPTimout:60 TCPTimeout:60 LogLevel:debug}"
time="2023-09-06 16:28:23" level=debug msg="tcp req:[chek.zennolab.com:80](https://chek.zennolab.com:80/)"
time="2023-09-06 16:29:00" level=debug msg="tcp req:[detect.expert:443](https://detect.expert/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[detect.expert:443](https://detect.expert/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[9.394679875.bash.ws:443](https://9.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[2.394679875.bash.ws:443](https://2.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[detect.expert:443](https://detect.expert/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[4.394679875.bash.ws:443](https://4.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[3.394679875.bash.ws:443](https://3.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[1.394679875.bash.ws:443](https://1.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[6.394679875.bash.ws:443](https://6.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[detect.id:443](https://detect.id/)"
time="2023-09-06 16:29:02" level=debug msg="tcp req:[5.394679875.bash.ws:443](https://5.394679875.bash.ws/)"
time="2023-09-06 16:29:02" level=debug msg="connect to [9.394679875.bash.ws:443](https://9.394679875.bash.ws/) failed" error="dial tcp: lookup [9.394679875.bash.ws](https://9.394679875.bash.ws/) on [8.8.8.8:53](https://8.8.8.8:53/): no such host"
time="2023-09-06 16:29:02" level=debug msg="connect to [2.394679875.bash.ws:443](https://2.394679875.bash.ws/) failed" error="dial tcp: lookup [2.394679875.bash.ws](https://2.394679875.bash.ws/) on [8.8.8.8:53](https://8.8.8.8:53/): no such host"
time="2023-09-06 16:29:03" level=error msg="conn handle" error=EOF
time="2023-09-06 16:29:03" level=debug msg="connect to [6.394679875.bash.ws:443](https://6.394679875.bash.ws/) failed" error="dial tcp: lookup [6.394679875.bash.ws](https://6.394679875.bash.ws/) on [8.8.8.8:53](https://8.8.8.8:53/): no such host"
time="2023-09-06 16:29:03" level=debug msg="tcp req:[7.394679875.bash.ws:443](https://7.394679875.bash.ws/)"
time="2023-09-06 16:29:03" level=debug msg="tcp req:[8.394679875.bash.ws:443](https://8.394679875.bash.ws/)"
time="2023-09-06 16:29:03" level=debug msg="tcp req:[10.394679875.bash.ws:443](https://10.394679875.bash.ws/)"
time="2023-09-06 16:29:03" level=debug msg="connect to [4.394679875.bash.ws:443](https://4.394679875.bash.ws/) failed" error="dial tcp: lookup [4.394679875.bash.ws](https://4.394679875.bash.ws/) on [8.8.8.8:53](https://8.8.8.8:53/): no such host"

the second site has udp connections, but for some reason the test fails

![image](https://github.com/0990/socks5/assets/72357001/c0e8569c-c30c-4073-b8e5-764a43ac2335)

time="2023-09-06 16:32:36" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:37" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:3478"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[18.195.48.248:3478](https://github.com/0990/socks5/issues/12)"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[18.195.48.224:443](https://github.com/0990/socks5/issues/12)"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[18.156.18.155:3478](https://github.com/0990/socks5/issues/12)"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[18.195.48.248:3478](https://github.com/0990/socks5/issues/12)"
time="2023-09-06 16:32:38" level=debug msg="udp  req:[global.turn.twilio.com](https://github.com/0990/socks5/issues/12).:443"

**Comment by bannyhm** [comment]
it seems that one of the programs that I used is not configured for udp support

![image](https://github.com/0990/socks5/assets/72357001/7737b1f6-f9c0-4bec-af6f-83f70ab1cc54)

**Comment by bannyhm** [comment]
I am very grateful to you for your help, you solved my problem very quickly. I still have questions about improving my wiring diagram. There is a telegram in my profile, write to me, I want to pay for help.

**Comment by 0990** [comment]
I am not well know about webRTC.Sorry,can't help more
