### ISSUE TITLE
架构的问题

### ISSUE THREAD

**Issue by Kaimar666** [0990/socks5#3]
你好，请问这里的Client和Server是和stunnel项目中的类似，代理包括代理客户端和代理服务端？还是只有一个代理服务端？

**Comment by Kaimar666** [comment]
然后，还有一个问题，这个项目转发消息是没有加密的是吧？

**Comment by 0990** [comment]
Client只是模拟将普通流量转成socks5流量用的测试代码，一般情况下使用第三方插件或工具。你应该只用代理服务端

**Comment by 0990** [comment]
此项目只根据[socks5协议](https://datatracker.ietf.org/doc/html/rfc1928)实现了服务端，并未增加额外功能，没有加密

**Comment by Kaimar666** [comment]
我现在是想实现stunnel项目那样的架构，但是那里没有使用SOCKS5代理协议，我想把这个SOCKS5代理加进去，需要怎么改一下呢？麻烦指点一下，谢谢。

**Comment by 0990** [comment]
你需要熟悉一下代码和socks5协议是什么，就可以进行下一步了

**Comment by Kaimar666** [comment]
好的，谢谢。如果有问题我再请教。
