### ISSUE TITLE
请教handleUDP函数的一个问题

### ISSUE THREAD

**Issue by drunkpig** [0990/socks5#6]
```python
func (p *Socks5Conn) handleUDP(req *Request) error {
	addr := p.conn.LocalAddr().(*net.TCPAddr)
	saddr := addr.String()
	//docker环境中获取不了本机正确ip,这时需要从事先设置的环境变量中获取
	if p.cfg.UDPAddr != "" {
		saddr = p.cfg.UDPAddr
	}
	bAddr, err := NewAddrByteFromString(saddr)
	if err != nil {
		p.conn.Write(NewReply(RepServerFailure, nil).ToBytes())
		return err
	}
	_, err = p.conn.Write(NewReply(RepSuccess, bAddr).ToBytes())
	if err != nil {
		return err
	}

	buf := make([]byte, 32)
	for {
		//p.conn.SetDeadline(time.Time{})
		_, err := p.conn.Read(buf)
		if err != nil {
			return err
		}
	}

	return nil
}
```
https://github.com/0990/socks5/blob/a9bb66c258309b1628bd1e84c58874d799b13028/conn_socks5.go#L141
上面函数里for{}之内，为甚么只有 `p.conn.Read(buf)`,却没有看到读取到之后做了哪些事情？是不是还没有实现

**Comment by 0990** [comment]
socks5建立udp代理时，先建立tcp连接，这个tcp连接在“握手”后的作用仅是： A UDP association terminates when the TCP connection that the UDP ASSOCIATE request arrived on terminates.
详见https://github.com/0990/socks5/blob/master/doc/rfc1928.txt

**Comment by 0990** [comment]
当UDP相关连的tcp连接关闭时也要关闭udp连接，这部分还未实现

**Comment by drunkpig** [comment]
> 

谢谢作者。
根据 
![image](https://user-images.githubusercontent.com/60862764/148941178-8fd8caf8-3487-4ff6-9053-744257757494.png)
可以知道在 上述函数的
`_, err = p.conn.Write(NewReply(RepSuccess, bAddr).ToBytes())` 这一行执行之后完全可以不用再写那个 for{}， 
那么可以解释一下写这个 for{}的作用是什么呢？

我猜测是防止客户端重试或者错误的发送的内容留在buf中影响下一次重试？

**Comment by drunkpig** [comment]
然后还有个问题，现在的 `NewUDPDatagram` 是不会自动分片的吗？

**Comment by 0990** [comment]
handleUDP()里for{}只是为了防止内核接收缓冲区满了导致连接异常关闭的情况，但这个tcp此时应该是无数据写入的，所以用处不大

**Comment by 0990** [comment]
> 然后还有个问题，现在的 `NewUDPDatagram` 是不会自动分片的吗？

不会自动分片

**Comment by 0990** [comment]
> handleUDP()里for{}只是为了防止内核接收缓冲区满了导致连接异常关闭的情况，但这个tcp此时应该是无数据写入的，所以用处不大

上面的表述也不准确，内核缓冲区满我还不确定会发生什么，只是尽量防止其发生

**Comment by drunkpig** [comment]
明白了
