### ISSUE TITLE
【bug】监听地址改成 127.0.0.1 不生效

### ISSUE THREAD

**Issue by dongshuyu** [0990/socks5#7]
监听地址改成 127.0.0.1 不生效

udp tcp 能否都添加 127.0.0.1 的本地监听地址

socks5 公开到公网，安全性不行，有本地使用的需求。

**Comment by 0990** [comment]
可以在防火墙上禁止这个端口的外网访问

**Comment by 0990** [comment]
加了新配置UDPListen，可以自定义监听地址了, https://github.com/0990/socks5/blob/master/doc/config.md
